name: spatio-temporal-fluct-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.7
  - pip >= 19.3.1
  - snakemake >= 5.9.1
  - pip:
    # - elephant >= 0.6.3
    - git+git://github.com/NeuralEnsemble/elephant.git #(pip install from git repo branch)
    # - neo > 0.8.0
    - git+https://github.com/NeuralEnsemble/python-neo.git
    - nixio >= 1.5.0b4
    - matplotlib
