name: visualizing_cortical_waves
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python == 3.8
  - pip == 20.1.1
  - snakemake == 5.18.1
  - pip:
    - elephant == 0.7.0
    # - neo == 0.8.0
    - git+https://github.com/NeuralEnsemble/python-neo.git
    - nixio == 1.5.0b4
    - matplotlib
    - lxml
    - rdflib
